### PR TITLE
Update cards-services.yaml

### PR DESCRIPTION
**Pull request by ndjones**
Removing the reference to JupyterHub, instead just to Jupyter

### CODE REVIEW

**Comment by CallumWalley** [comment]
@ndjones Is this how we will be referring to the service now? 
It's worth noting, the 'Lab' features (file browser, proxy extensions, terminal, etc) are the draw for most people.

**Comment by ndjones** [comment]
The change is away from "Hub". the service is jupyter.nesi.org.nz, so jupyter is the more general name we use. adding "Lab" doesn't make much difference to me, though I appreciate it refers to the IDE which supports jupyter notebooks among other things. 

While I'd tend to veer away from product names usually, Jupyter (and R and Python) are the things people come to know pretty quickly. Whether the descrimination to "Lab" means much to a broader number, or is just more precise.. I'd tend towards shorter simpler rather than absolute precision for the few?

**Comment by ndjones** [comment]
@CallumWalley happy for you all to make a call on that or JupyterLab if that's considered usefully concise. I think we've used all three throughout our docs, so consistency is perhaps the best outcome, alongside removing "Hub"?

**Comment by CallumWalley** [comment]
Don't really have a preference. Just wanted the reasoning so we can aim for some consistency.

**Pull request merged**
